[control]
server-a ansible_host=xxx.xxx.xxx.xxx  # さくらVPSのIPアドレス1

[app_db]
server-b ansible_host=xxx.xxx.xxx.xxx  # さくらVPSのIPアドレス2

[monitor]
server-c ansible_host=xxx.xxx.xxx.xxx  # さくらVPSのIPアドレス3

[all:vars]
ansible_user=root
ansible_port=22
# ★完全自動化用の環境スイッチ（さくらVPSは本番なのでtrue）
is_production=true