[control]
server-a ansible_host=10.149.245.110 prometheus_internal_url="http://10.149.245.116:9090"

[app]
server-b ansible_host=10.149.245.115

[monitor]
server-c ansible_host=10.149.245.116

[all:vars]
ansible_user=vagrant
ansible_ssh_pass=vagrant
# ★ここで「鍵ではなく、パスワード認証を強制する」という魔法のスイッチをオンにする
ansible_ssh_authentication_method=password
ansible_port=22
is_production=false