[control]
server-a ansible_host=10.149.245.110

[app]
server-b ansible_host=10.149.245.115

[monitor]
server-c ansible_host=10.149.245.116

[all:vars]
ansible_user=vagrant
ansible_ssh_pass=vagrant
ansible_port=22
# ★完全自動化用の環境スイッチ（Vagrantは本番ではないのでfalse）
is_production=false